#!/usr/bin/env bash

set -e

echo "WARNING!! This script REMOVE your starwars containers and database, REMOVING ALL DATA!"
read -p "Are you sure you want to delete all data? (y/N): " -n 1 -r
echo    # (optional) move to a new line
if [[ ! $REPLY =~ ^[Yy]$ ]] ; then
    exit 1
fi

cd "$(dirname "$0")/.."

# echo "==> Removing old containers and database"
# docker compose down -v

# echo "==> Rebuilding containers"
# docker compose up --build -d

dropdb --if-exists starwars
createdb starwars

echo "==> App is now ready to go! Run the following commands to get started:"

echo "Migrate the DB:"
echo "\$ docker exec -it reinjan-starwars-web python manage.py migrate"

echo "Import characters:"
echo "\$ docker exec -it reinjan-starwars-web python manage.py import_characters starwars-data.json"

echo "Create a superuser:"
echo "\$ docker exec -it reinjan-starwars-web python manage.py createsuperuser"
