# Generated by Django 5.1.7 on 2025-03-12 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        default=dict,
                        help_text="Extra defining attributes of the character",
                        null=True,
                    ),
                ),
                (
                    "born",
                    models.IntegerField(
                        help_text="Year the character was born", null=True
                    ),
                ),
                (
                    "died",
                    models.IntegerField(
                        help_text="Year the character is deceased", null=True
                    ),
                ),
                (
                    "died_location",
                    models.CharField(
                        help_text="Location where the character died",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "eye_color",
                    models.CharField(
                        help_text="Eye color of the character",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        help_text="Gender of the character",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "hair_color",
                    models.CharField(
                        help_text="Hair color of the character",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.FloatField(help_text="Height of the character", null=True),
                ),
                (
                    "homeworld",
                    models.CharField(
                        help_text="Homeworld of the character",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        help_text="URL to the character's image", null=True
                    ),
                ),
                (
                    "is_placeholder",
                    models.BooleanField(
                        default=False,
                        help_text="Placeholder character referenced by other characters",
                    ),
                ),
                (
                    "mass",
                    models.FloatField(help_text="Mass of the character", null=True),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the character", max_length=255, null=True
                    ),
                ),
                (
                    "reference_id",
                    models.IntegerField(
                        help_text="Reference ID of the character",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "skin_color",
                    models.CharField(
                        help_text="Skin color of the character",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        help_text="Species of the character", max_length=255, null=True
                    ),
                ),
                (
                    "wiki",
                    models.URLField(
                        help_text="URL to the character's wiki page", null=True
                    ),
                ),
                (
                    "affiliations",
                    models.ManyToManyField(
                        help_text="Affiliations of the character",
                        related_name="characters",
                        to="characters.affiliation",
                    ),
                ),
                (
                    "former_affiliations",
                    models.ManyToManyField(
                        help_text="Former affiliations of the character",
                        related_name="former_characters",
                        to="characters.affiliation",
                    ),
                ),
                (
                    "masters",
                    models.ManyToManyField(
                        help_text="Masters of the character",
                        related_name="apprentices",
                        to="characters.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="characters.character",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="characters.team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team", "character")},
            },
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ManyToManyField(
                help_text="Members of the team",
                related_name="teams",
                through="characters.TeamMembership",
                to="characters.character",
            ),
        ),
    ]
